import 'package:app_usuario_cooper/app/modules/home/domain/entity/cards_entity.dart';
import 'package:app_usuario_cooper/app/modules/home/domain/helpers/get_cards_exception.dart';

class GetCardsMapper {
  GetCardsMapper._();

  static Map<String, dynamic> toMap(CardsEntity cards) {
    return <String, dynamic>{
      'nomeUsuario': cards.nomeUsuario,
      'cartNrUnico': cards.cartNrUnico,
      'cartCodMask': cards.cartCodMask,
      'cartNome': cards.cartNome,
      'empresa': cards.empresa,
      'origem': cards.origem,
      'status': cards.status,
      'imagem': cards.imagem,
      'contCod': cards.contCod,
      'banCod': cards.banCod,
      'cartAlias': cards.cartAlias,
      'bloqCod': cards.bloqCod,
      'envioComunicadoSms': cards.envioComunicadoSms,
      'envioComunicadoEmail': cards.envioComunicadoEmail,
      'codProtocolo': cards.codProtocolo,
      'codEtapaProt': cards.codEtapaProt,
      'descEtapaProt': cards.descEtapaProt,
      'permiteTransferencia': cards.permiteTransferencia,
      'envioFatura': cards.envioFatura,
      'dtBloq': cards.dtBloq,
      'classificacao': cards.classificacao,
      'recargaCelular': cards.recargaCelular,
      'diaDtVenc': cards.diaDtVenc,
      'permiteAltDtVenc': cards.permiteAltDtVenc,
      'permiteAltLimite': cards.permiteAltLimite,
      'vlrLimiteAtual': cards.vlrLimiteAtual,
      'vlrLimiteMaximo': cards.vlrLimiteMaximo,
      'temLimiteDetalhado': cards.temLimiteDetalhado,
      'melhorDataCompra': cards.melhorDataCompra,
      'possuiSeguroSancor': cards.possuiSeguroSancor,
      'permiteDoacao': cards.permiteDoacao,
      'vlrMinSaque': cards.vlrMinSaque,
      'codigoPlanoSeguro': cards.codigoPlanoSeguro,
      'dataPlanoSeguro': cards.dataPlanoSeguro,
      'permiteSaqueEmprest': cards.permiteSaqueEmprest,
      'permiteTransfEmprest': cards.permiteTransfEmprest,
      'limiteEmprestimo': cards.limiteEmprestimo,
      'saldoEmprestimo': cards.saldoEmprestimo,
      'cartSit': cards.cartSit,
      'limiteBanEmprestimo': cards.limiteBanEmprestimo,
      'vlrMaxSaque': cards.vlrMaxSaque,
      'vlrMinTransf': cards.vlrMinTransf,
      'vlrMaxTransf': cards.vlrMaxTransf,
      'flgCashback': cards.flgCashback,
      'flgPrevcash': cards.flgPrevcash,
      'flgGiftplus': cards.flgGiftplus,
      'possuiSeguroGenerali': cards.possuiSeguroGenerali,
      'codPlanoSegGenerali': cards.codPlanoSegGenerali,
      'dtPlanoSegGenerali': cards.dtPlanoSegGenerali,
      'possuiCertificado': cards.possuiCertificado,
      'flagClubBloqueado': cards.flagClubBloqueado,
      'flagCashbackBloqueado': cards.flagCashbackBloqueado,
      'flgProvisorio': cards.flgProvisorio,
      'flgDesbloqueiaDefinitivo': cards.flgDesbloqueiaDefinitivo,
      'flgShoppingCooper': cards.flgShoppingCooper,
      'flgCpfIgual': cards.flgCpfIgual,

    };
  }

  static CardsEntity fromMap(Map<String, dynamic> map) {
    try {
      return CardsEntity(
          nomeUsuario: map['NOME_USUARIO'] ?? '',
          cartNrUnico: map['CART_NR_UNICO'] ?? '',
          cartCodMask: map['CART_COD_MASK'] ?? '',
          cartNome: map['CART_NOME'] ?? '',
          empresa: map['EMPRESA'] ?? '',
          origem: map['ORIGEM'] ?? '',
          status: map['STATUS'] ?? '',
          imagem: map['IMAGEM'] ?? '',
          contCod: map['CONT_COD'] ?? '',
          banCod: map['BAN_COD'] ?? '',
          cartAlias: map['CART_ALIAS'] ?? '',
          bloqCod: map['BLOQ_COD'] ?? '',
          envioComunicadoSms: map['ENVIO_COMUNICADO_SMS'] ?? '',
          envioComunicadoEmail: map['ENVIO_COMUNICADO_EMAIL'] ?? '',
          codProtocolo: map['COD_PROTOCOLO'] ?? '',
          codEtapaProt: map['COD_ETAPA_PROT'] ?? '',
          descEtapaProt: map['DESC_ETAPA_PROT'] ?? '',
          permiteTransferencia: map['PERMITE_TRANSFERENCIA'] ?? '',
          envioFatura: map['ENVIO_FATURA'] ?? '',
          dtBloq: map['DT_BLOQ'] ?? '',
          classificacao: map['CLASSIFICACAO'] ?? '',
          recargaCelular: map['RECARGA_CELULAR'] ?? '',
          diaDtVenc: map['DIA_DT_VENC'] ?? '',
          permiteAltDtVenc: map['PERMITE_ALT_DT_VENC'] ?? '',
          permiteAltLimite: map['PERMITE_ALT_LIMIT'] ?? '',
          vlrLimiteAtual: map['VLR_LIMIT'] ?? '',
          vlrLimiteMaximo: map['VLR_MAXIMO'] ?? '',
          temLimiteDetalhado: map['TEM_LIMITE_DETALHADO'] ?? '',
          melhorDataCompra: map['MELHOR_DATA_COMPRA'] ?? '',
          possuiSeguroSancor: map['POSSUI_SEGURO_SANCOR'] ?? '',
          permiteDoacao: map['PERMITE_DOACAO'] ?? '',
          vlrMinSaque: map['VLR_MIN_SAQUE'] ?? '',
          codigoPlanoSeguro: map['CODIGO_PLANO_SEGURO'] ?? '',
          dataPlanoSeguro: map['DATA_PLANO_SEGURO'] ?? '',
          permiteSaqueEmprest: map['PERMITE_SAQUE_EMPREST'] ?? '',
          permiteTransfEmprest: map['PERMITE_TRANSF_EMPREST'] ?? '',
          limiteEmprestimo: map['LIMITE_EMPRESTIMO'] ?? '',
          saldoEmprestimo: map['SALDO_EMPRESTIMO'] ?? '',
          cartSit: map['CART_SIT'] ?? '',
          limiteBanEmprestimo: map['LIMITE_BAN_EMPRESTIMO'] ?? '',
          vlrMaxSaque: map['VLR_MAX_SAQUE'] ?? '',
          vlrMinTransf: map['VLR_MIN_TRANSF'] ?? '',
          vlrMaxTransf: map['VLR_MAX_TRANSF'] ?? '',
          flgCashback: map['FLG_CASHBACK'] ?? '',
          flgPrevcash: map['FLG_PREVCASH'] ?? '',
          flgGiftplus: map['FLG_GIFTPLUS'] ?? '',
          possuiSeguroGenerali: map['POSSUI_SEGURO_GENERALI'] ?? '',
          codPlanoSegGenerali: map['COD_PLANO_SEG_GENERALI'] ?? '',
          dtPlanoSegGenerali: map['DT_PLANO_SEG_GENERALI'] ?? '',
          possuiCertificado: map['POSSUI_CERTIFICADO'] ?? '',
          flagClubBloqueado: map['FLAG_CLUB_BLOQUEADO'] ?? '',
          flagCashbackBloqueado: map['FLAG_CASHBACK_BLOQUEADO'] ?? '',
          flgProvisorio: map['FLG_PROVISORIO'] ?? '',
          flgDesbloqueiaDefinitivo: map['FLG_DESBLOQUEIA_DEFINITIVO'] ?? '',
          flgShoppingCooper: map['FLG_SHOPPING_COOPER'] ?? '',
          flgCpfIgual: map['FLG_CPF_IGUAL'] ?? '',
          );
    } on GetCardsMapperException {
      rethrow;
    }
  }
}
